version: '3'

services:
  bot:
    build: .
    volumes:
      - ./src/:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  updater:
    build: .
    command: ["python", "rates_scheduler.py"]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
